include:
  - project: graphaware/devops/gitlab-ci-templates
    file: neo4j-framework-template.yml

stages:
  - install
  - test
  - deploy
  - postDeploy
  - triggers

frameworkVersionBump:
  script:
    - NEW_VERSION="${VERSION%.*}.$((${VERSION##*.}+1))-SNAPSHOT"
    - CUSTOM_SPACE='    ' #otherwise bash joins spaces into one
    - CHANGELOG_MSG="${CHANGELOG_MSG:-${VERSION}:\n${CUSTOM_SPACE}- Upgrade to Neo4j ${VERSION%.*}}\n"
    - echo -e "$CHANGELOG_MSG\n$(cat changes.txt)" > changes.txt # add the message into changes.txt, -e enable special characters (\n)
    - git commit -a -m "Release with new neo4j version"  #You can add edition of a file to pom using ant-plugin. You can connect it to the goals of the maven release plugin. But this plugin won't commit anything else but POMs!!!
    - mvn release:clean release:prepare
      $MAVEN_CLI_OPTS
      -DreleaseVersion=$VERSION
      -DdevelopmentVersion=$NEW_VERSION
      -Dtag="Version-${VERSION}"
    - mvn release:perform
      $MAVEN_CLI_OPTS
  only:
    refs:
      - master
    variables:
      - $VERSION

uploadToS3:
  before_script:
    - FROM="target/checkout/build/graphaware-framework-server/target/graphaware-server-all-$VERSION.jar"
    - TO="$AWS_PATH/graphaware-server-all-$VERSION.jar"

#Delay triggers by 30 minutes - maven central needs some time to process the artifacts
delay30mins:
  extends: .delay30mins

#trigger template
.trigger:
  stage: triggers
  variables:
    PARENT_VERSION: $VERSION
  trigger:
    strategy: depend
  only:
    refs:
      - master
    variables:
      - $VERSION

triggerUUID:
  extends: .trigger
  trigger:
    project: GraphAware/neo4j-plugins/neo4j-uuid

triggerRestTest:
  extends: .trigger
  trigger:
    project: GraphAware/neo4j-plugins/neo4j-resttest

triggerExpire:
  extends: .trigger
  trigger:
    project: GraphAware/neo4j-plugins/neo4j-expire

triggerRecommendation:
  extends: .trigger
  trigger:
    project: GraphAware/neo4j-plugins/neo4j-reco

triggerTriggers:
  extends: .trigger
  trigger:
    project: GraphAware/neo4j-plugins/neo4j-triggers

triggerTimetree:
  extends: .trigger
  trigger:
    project: GraphAware/neo4j-plugins/neo4j-timetree

triggerGAstarter:
  extends: .trigger
  trigger:
    project: GraphAware/neo4j-plugins/graphaware-starter

triggerRecommendationsMeetup:
  extends: .trigger
  trigger:
    project: GraphAware/neo4j-plugins/recommendations-meetup

#neo4j-to-elasticsearch is launched from UUID as it depends on it